name: module1
description: A new flutter module project.
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  core:
    path: ../core

  components:
    path: ../components
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.example.module1
    iosBundleIdentifier: com.example.module1
